QMAKE_DEPENDS_LIBGLESV2_CC =
QMAKE_DEPENDS_LIBGLESV2_LD =
QMAKE_INCDIR_LIBGLESV2 = 
QMAKE_DEFINES_LIBGLESV2 = 
QMAKE_LIBS_LIBGLESV2 =
QMAKE_LIBS_LIBGLESV2_DEBUG = C:/qsc/5.15.3_dolphin.amd64.build/qtbase/lib/libGLESv2d.lib
QMAKE_LIBS_LIBGLESV2_RELEASE = C:/qsc/5.15.3_dolphin.amd64.build/qtbase/lib/libGLESv2.lib
