QMAKE_DEPENDS_FREETYPE_CC =
QMAKE_DEPENDS_FREETYPE_LD =
QMAKE_INCDIR_FREETYPE = $$[QT_INSTALL_HEADERS]/qtfreetype
QMAKE_DEFINES_FREETYPE = 
QMAKE_LIBS_FREETYPE =
QMAKE_LIBS_FREETYPE_DEBUG = C:/qsc/5.15.3_dolphin.amd64.build/qtbase/lib/qtfreetyped.lib
QMAKE_LIBS_FREETYPE_RELEASE = C:/qsc/5.15.3_dolphin.amd64.build/qtbase/lib/qtfreetype.lib
