QMAKE_DEPENDS_LIBEGL_CC =
QMAKE_DEPENDS_LIBEGL_LD =
QMAKE_INCDIR_LIBEGL = 
QMAKE_DEFINES_LIBEGL = 
QMAKE_LIBS_LIBEGL =
QMAKE_LIBS_LIBEGL_DEBUG = C:/qsc/5.15.3_dolphin.amd64.build/qtbase/lib/libEGLd.lib
QMAKE_LIBS_LIBEGL_RELEASE = C:/qsc/5.15.3_dolphin.amd64.build/qtbase/lib/libEGL.lib
