/* This file was generated by syncqt. */
#ifndef QT_QTSVGWIDGETS_VERSION_H
#define QT_QTSVGWIDGETS_VERSION_H

#define QTSVGWIDGETS_VERSION_STR "6.8.3"

#define QTSVGWIDGETS_VERSION 0x060803

#endif // QT_QTSVGWIDGETS_VERSION_H
